rendering:
  resolution:
    width: 1920
    height: 1080
  frame_rate: 60
  clear_color:
    r: 0.1
    g: 0.1
    b: 0.1
    a: 1.0
  shaders:
    default_vertex_shader: "assets/shaders/default_vertex.glsl"
    default_fragment_shader: "assets/shaders/default_fragment.glsl"
  materials:
    default_material:
      ambient:
        r: 0.2
        g: 0.2
        b: 0.2
      diffuse:
        r: 0.8
        g: 0.8
        b: 0.8
      specular:
        r: 1.0
        g: 1.0
        b: 1.0
      shininess: 32
  lighting:
    ambient_light:
      intensity: 0.5
    directional_light:
      direction:
        x: -1.0
        y: -1.0
        z: -1.0
      intensity: 1.0
  post_processing:
    enabled: true
    effects:
      - bloom
      - motion_blur
      - vignette