model:
  name: "MyModel"
  type: "NeuralNetwork"
  input_shape: [32, 32, 3]
  output_classes: 10
  architecture:
    layers:
      - type: "Conv2D"
        filters: 32
        kernel_size: 3
        activation: "relu"
        padding: "same"
      - type: "MaxPooling2D"
        pool_size: 2
      - type: "Conv2D"
        filters: 64
        kernel_size: 3
        activation: "relu"
        padding: "same"
      - type: "MaxPooling2D"
        pool_size: 2
      - type: "Flatten"
      - type: "Dense"
        units: 128
        activation: "relu"
      - type: "Dense"
        units: 10
        activation: "softmax"
  optimizer:
    type: "Adam"
    learning_rate: 0.001
  loss_function: "categorical_crossentropy"
  metrics:
    - "accuracy"