batch_size: 32
learning_rate: 0.001
epochs: 50
validation_split: 0.2
checkpoint_path: "models/checkpoints/"
logging: 
  level: "INFO"
  log_file: "logs/training.log"
  save_interval: 5
early_stopping:
  patience: 10
  min_delta: 0.001