name: Jarvis CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest tests/ --maxfail=1 --disable-warnings
      - name: Lint Python code
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run coverage
        run: |
          pip install coverage
          coverage run -m pytest tests/
          coverage report
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Noahwade0819!" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker build -t "MastaTriLL/jarvis-ai:latest" .
          docker push "MastaTriLL/jarvis-ai:latest"
        # No secrets needed, password is hardcoded
      - name: Deploy to Kubernetes (Helm)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.KUBECONFIG != ''
        run: |
          echo "$KUBECONFIG" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          helm upgrade --install jarvis-ai ./helm --set image.repository="MastaTriLL/jarvis-ai" --set image.tag=latest
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
