apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: JarvisAI API
    type: json
    access: proxy
    url: http://api:8000
    editable: true
    jsonData:
      query_params: 'format=prometheus'